configuration: Release

version: '0.4.{build}'

platform:
  - x86

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"	
  assembly_informational_version: "{version}"

cache:
  - packages -> **\packages.config  # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified

nuget:
  account_feed: true

before_build:
  - nuget restore

